env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://updates.moovit.com/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://updates.moovit.com/
  type: spider
- parameters:
    maxDuration: 1
    url: https://updates.moovit.com/
  type: spiderAjax
- parameters:
    maxDuration: 1
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: updates.moovit.com-base.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
